select wd.WORKINGDAY, wt.id, wt.WORKINGTIME, wpd.DESCRIPTION, wp.WPNAME, pi."NAME"
  from APP.WORKINGDAY wd LEFT JOIN APP.WORKINGTIME wt ON wd.ID = wt.WORKINGDAY_ID  
                         LEFT JOIN APP.WORKPACKAGEDESCRIPTION wpd ON wt.WORKPACKAGEDESCRIPTION_ID = wpd.ID
                         LEFT JOIN APP.WORKPACKAGE wp ON wt.WORKPACKAGE_ID = wp.ID
                         LEFT JOIN APP.PROJECTINFORMATION pi ON wp.PROJECTINFORMATION_ID = pi.ID
 order by wd.WORKINGDAY desc;

--delete from APP.WORKINGTIME;
--delete from APP.WORKINGDAY;
--delete from APP.WORKPACKAGEDESCRIPTION;
