/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sourcecoding.pb.business;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author Matthias
 */
@ApplicationPath("rest")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.sourcecoding.pb.business.user.boundary.IndividualService.class);
        resources.add(com.sourcecoding.pb.business.workinghours.boundary.WorkingHours.class);
        resources.add(com.sourcecoding.pb.business.perdiemcharges.boundary.PerDiemService.class);
        resources.add(com.sourcecoding.pb.business.project.boundary.ProjectServices.class);
        resources.add(com.sourcecoding.pb.business.authentication.boundary.AuthLinkedInService.class);
        resources.add(com.sourcecoding.pb.business.authentication.boundary.AuthService.class);
        try {
            Class<?> jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }
}
