/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sourcecoding.pb.business.restconfig;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author Matthias
 */
@ApplicationPath("rest")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        try {
            Class jsonProvider = Class.forName("org.glassfish.jersey.jackson.JacksonFeature");
            // Class jsonProvider = Class.forName("org.glassfish.jersey.moxy.json.MoxyJsonFeature");
            // Class jsonProvider = Class.forName("org.glassfish.jersey.jettison.JettisonFeature");
            resources.add(jsonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(com.sourcecoding.pb.business.authentication.boundary.AuthLinkedInService.class);
        resources.add(com.sourcecoding.pb.business.authentication.boundary.AuthService.class);
        resources.add(com.sourcecoding.pb.business.individuals.boundary.IndividualService.class);
        resources.add(com.sourcecoding.pb.business.individuals.boundary.IndividualsResource.class);
        resources.add(com.sourcecoding.pb.business.meta.boundary.VersionService.class);
        resources.add(com.sourcecoding.pb.business.perdiemcharges.boundary.PerDiemService.class);
        resources.add(com.sourcecoding.pb.business.project.boundary.ProjectServices.class);
        resources.add(com.sourcecoding.pb.business.resources.boundary.ResourcesResource.class);
        resources.add(com.sourcecoding.pb.business.timerecording.boundary.TimeRecordingService.class);
        resources.add(com.sourcecoding.pb.business.vacation.boundary.IndividualVacationResource.class);
        resources.add(com.sourcecoding.pb.business.vacation.boundary.TasksResource.class);
        resources.add(com.sourcecoding.pb.business.vacation.boundary.VacationService.class);
        resources.add(com.sourcecoding.pb.business.workinghours.boundary.WorkingHours.class);
    }
}
